;;;;;;;;;;;;
;; THIS FILE IS ALL ABOUT WRITING HELLO WORLD TO A SCREEN BUFFER
;; THE AMBITION IS TO ALLOCATE A BYTE ARRAY TO EACH INDIVUAL LETTER TO
;; BE RENDERED ON SCREEN
;;;;;;;;;;;;

SECTION .RAM

X EQU $00FF0000 
Y EQU $00FF0000+1

SECTION .VDP

VDP_DATA EQU $C00000  ;;; WORD AND LONG READ ONLY
VDP_CTRL EQU $C00004  ;;; WORD AND LONG WRITES ONLY

SECTION .MAIN
GLOBAL _START

_START:
